### ISSUE TITLE
Instapaper introduced tags

### ISSUE THREAD

**Issue by heavelock** [tdhooten/Polyglot#2]
Hey!

It looks like your implementation of support for Instapaper is based on this statement:
> Instapaper's organizational tools are extremely limited. First of all it does not support tags;

Since yesterday, they do support tags:
https://blog.instapaper.com/post/765771980408569856/tags

Right in time for the Omnivore exodus

**Comment by tdhooten** [comment]
Thank you, I just added support for Instapaper tags on both import and export.
